### ISSUE TITLE
Overlay does not consider possibility of streamer hovering the hero leading to potential reveal.

### ISSUE THREAD

**Issue by Aluerie** [dotabod/backend#169]
Just look at this screenshot from Gorgc stream VOD
![image](https://user-images.githubusercontent.com/33165440/216319077-fd920407-ef4f-49cc-82d7-bb7d0168b759.png)

He is clearly hovering Lycan and potential streamsniper might notice it and maybe conclude that streamer wants to pick this specific hero. 

"Sélect two heroes" probably isn't important bcs you can see what enemies picked/gonna pick anyway.

**Comment by dankYoff** [comment]
https://user-images.githubusercontent.com/91318807/216327280-b472eb07-90d1-4611-9fb3-0ef97e740a00.mp4

**Comment by Geczy** [comment]
@Aluerie do you mute using dotabod obs scene switcher? because if its not muted, it seems like even if i block the picks further, snipers can still hear the hero you pick

but i also dont want to block higher because i want that dynamic text to not be blocked by my overlay, here:

(your team is losing gold, and this msg changes a lot)

![Image](https://user-images.githubusercontent.com/1036968/216403206-8bf2c7d6-20f0-49d2-ac9f-51a8b6669350.png)

**Comment by Aluerie** [comment]
Hmm, okay I see, that's a head-scratcher. But myself, I don't think I ever paid attention to this white text, it's the money sound that gives it away... but if we consider mute-feature to be present, hm, idk.

> do you mute 
myself, I'm yet to stream dota this year, sorry, cant give feedback from streamer-side.

--- 
However, opinion, If I were an elite mmr paranoid streamer I would probably exactly prefer some full-screen-cover-image/overlay that only shows player names and mutes dota sounds than have these possibilités to leak my hero through sounds, hero appearing animation, hovering, etc. And some overlay to hide q for queue snipers :x

oh well, sorry

**Comment by Geczy** [comment]
yeah, the thing is gorgc has been streaming with a hero pick blocker for years now. you can check his older vod to see, he was only blocking his allied player picks. he didn't even block bans or anything

so im thinking, since no one has really asked for a _full_ hero pick blocker screen phase, maybe its not that important

i think only waga is using a full screen overlay, but he set that up using the dotabod obs scene switcher because he's meticulous like that

i think it'd be really jarring to see the whole screen blocked for most casual streamers that have chatters, like grubby or gorgc. i have a feeling it wont be welcome

**Comment by dankYoff** [comment]
@Aluerie use OBS scene switcher created in dotabod. 
Unfortunately, nothing is perfect, so if you want to completely get rid of stream snipers, here is:

![зображення](https://user-images.githubusercontent.com/91318807/216487025-880e8019-2678-4098-bab2-1a6ea66c1f7e.png)
