### ISSUE TITLE
wl bug (not scored after stuck)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#196]
https://www.twitch.tv/videos/1730501814?t=2h18m26s

**Comment by Geczy** [comment]
i think i was rebooting server right at that time

**Comment by Geczy** [comment]
i rebooted 3 times today, all in UTC tz

henry streaming since 6:18pm my local GMT tz

timestamp is around 2h 18m from his start time, so thats 8:36pm GMT

convert this time to UTC and thats 2:36 am, within a few minutes of dotabod being rebooted, so i think its related...

![image](https://user-images.githubusercontent.com/1036968/217150584-d8f06eae-ea0b-4d9f-9aae-cdf58ac399fb.png)

![image](https://user-images.githubusercontent.com/1036968/217150506-ece0ea54-a124-4a13-80a6-7588513b4509.png)

![image](https://user-images.githubusercontent.com/1036968/217150769-86742252-7bdd-4454-abaa-b71907454f11.png)

![image](https://user-images.githubusercontent.com/1036968/217150802-8010252d-1702-4b20-b182-5464037e510a.png)
